routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/about', function() {
    return view('about');
});

Route::get('/privacypolicy', function() {
	return view('privacypolicy');
});

Route::get('/google-drive', function() {
    return view('manuscripts.images');
})->name('google-drive');

// Manuscript viewer route
Route::get('/manuscripts/{manuscript}/viewer', 'ManuscriptController@viewer')->name('manuscripts.viewer');

// Search routes                                        
Route::get('/manuscripts/search', 'ManuscriptController@showSearchForm')->name('manuscripts.showSearchForm');
Route::post('/manuscripts/search', 'ManuscriptController@search')->name('manuscripts.search');
Route::post('/manuscripts/search_one', 'ManuscriptController@searchOne')->name('manuscripts.searchOne');
Route::post('/manuscripts/dd', 'ManuscriptController@dumpAndDie')->name('dumpAndDie');
// Manuscript resource controller routes
Route::resource('manuscripts', 'ManuscriptController');

// Authentication
Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('/home', 'HomeController@index')->name('home');

app/Manuscript.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manuscript extends Model
{
    protected $fillable = [
        'physical_location',
        'classmark',
        'subject',
        'subject_other_lang',
        'author',
        'place_of_origin',
        'date_of_creation',
        'associated_persons',
        'physical_description',
        'material',
        'format',
        'binding',
        'images',
        'user_id',
        'preview_image',
    ];
}

app/Http/Controllers/ManuscriptController.php
<?php

namespace App\Http\Controllers;

use App\Manuscript;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Collection;
use App\Controllers\Debugbar;



class ManuscriptController extends Controller
{
    public function __construct() {
        $this->middleware('auth')->only(['create', 'store','edit','update','destroy']);
    }


    private function formatImageString(String $imageString) {
        $images = explode("\r\n", $imageString);
        $newImages = array();
        foreach($images as &$image) {
            $newImage = str_replace("open?", "uc?", $image);
            array_push($newImages, $newImage);
        }
        return join(",", $newImages);

    }

    private static function createImageArray(String $imagesString)  {
        $images = explode(",", $imagesString);
         $imageData = [];
         foreach($images as $img) {
             $strParts = explode("|", $img);
             $width_height = explode(":", $strParts[1]);
             $imageData[] = ['image_link' =>  $strParts[0], 'width' => $width_height[0], 'height' => $width_height[1]];
         }
        return $imageData;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $manuscripts = Manuscript::all();
        return view('manuscripts.index', ['manuscripts' => $manuscripts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manuscripts.create')
            ->with('manuscript', (new Manuscript()));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        
        $validatedData = $request->validate([
            'physical_location' => 'required',
            'classmark' => 'required',
            'subject' => 'required',
            'subject_other_lang' => 'required',
            'author' => 'required',
            'place_of_origin'  => 'required',
            'date_of_creation' => 'required',
            'associated_persons'  => 'required',
            'physical_description' => 'required',
            'material' => 'required',
            'format' => 'required',
            'binding' => 'required',
            'images' => 'required',
            'preview_image' => 'required',
        ]);

        \Debugbar::addMessage($request, 'POST request');

        $users = DB::table('users')->get();
        $user = $users[0];
        $formattedImageString = $this->formatImageString($request->images);
        $manuscript = Manuscript::create([
            'physical_location' => $request->physical_location,
            'classmark' => $request->classmark,
            'subject' => $request->subject,
            'subject_other_lang' => $request->subject_other_lang,
            'author' => $request->author,
            'place_of_origin' => $request->place_of_origin,
            'date_of_creation'=>$request->date_of_creation,
            'associated_persons' => $request->associated_persons,
            'physical_description' => $request->physical_description,
            'material'=> $request->material,
            'format' => $request->format,
            'binding' => $request->binding,
            'images' => $formattedImageString,
            'preview_image' => $request->preview_image,
            'user_id' => Auth::id(),
        ]);
        print('Big purrs');
        $manuscriptImages = $this->createImageArray($formattedImageString);
        return view('manuscripts.show', ['manuscript' => $manuscript, 'manuscriptImages' => $manuscriptImages]);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Manuscript  $manuscript
     * @return \Illuminate\Http\Response
     */
    public function show(Manuscript $manuscript)
    { 
        $manuscriptImages = $this->createImageArray($manuscript->images);
        return view('manuscripts.show', ['manuscript' => $manuscript, 'manuscriptImages' => $manuscriptImages]);
    }

    public function viewer(Manuscript $manuscript) {
        $manuscriptImages = $this->createImageArray($manuscript->images);
        return view('manuscripts.viewer', ['manuscript' => $manuscript, 'manuscriptImages' => $manuscriptImages]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Manuscript  $manuscript
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $manuscript = Manuscript::findOrFail($id);
        $images = str_replace(",", "\n", $manuscript->images);
        return view('manuscripts.edit', ['manuscript' => $manuscript, 'images' => $images]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Manuscript  $manuscript
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $manuscript = Manuscript::findOrFail($id);
        $formattedImageString = $this->formatImageString($request->images);
        $manuscript->physical_location = $request->physical_location;
        $manuscript->classmark = $request->classmark;
        $manuscript->subject = $request->subject;
        $manuscript->subject_other_lang = $request->subject_other_lang;
        $manuscript->author = $request->author;
        $manuscript->place_of_origin = $request->place_of_origin;
        $manuscript->date_of_creation = $request->date_of_creation;
        $manuscript->associated_persons = $request->associated_persons;
        $manuscript->physical_description = $request->physical_description;
        $manuscript->material= $request->material;
        $manuscript->format = $request->format;
        $manuscript->binding = $request->binding;
        $manuscript->images = $formattedImageString;
        $manuscript->preview_image = $request->preview_image;
        $manuscript->save();

        return view('manuscripts.show', ['manuscript' => $manuscript, 'manuscriptImages' => $this->createImageArray($manuscript->images)]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Manuscript  $manuscript
     * @return \Illuminate\Http\Response
     */
    public function destroy(Manuscript $manuscript)
    {
        //
    }

    public function showSearchForm() {
        return view('manuscripts.search');
    }

    public function search(Request $request) {
        $param = $request->search_parameters;
        $searchResults = new Collection();
        $pl_res = Manuscript::where('physical_location', 'LIKE','%'.$param.'%')->get();
        $cm_res = Manuscript::where('classmark', 'LIKE','%'.$param.'%')->get();
        $po_res = Manuscript::where('place_of_origin', 'LIKE','%'.$param.'%')->get();
        $doc_res = Manuscript::where('date_of_creation', 'LIKE','%'.$param.'%')->get();
        $sub_res = Manuscript::where('subject', 'LIKE','%'.$param.'%')->get();
        $subol_res = Manuscript::where('subject_other_lang', 'LIKE','%'.$param.'%')->get();
        $aut_res = Manuscript::where('author', 'LIKE','%'.$param.'%')->get();
        $aspn_res = Manuscript::where('associated_persons', 'LIKE','%'.$param.'%')->get();
        $pd_res = Manuscript::where('physical_description', 'LIKE','%'.$param.'%')->get();
        $mat_res = Manuscript::where('material', 'LIKE','%'.$param.'%')->get();
        $fmt_res = Manuscript::where('format', 'LIKE','%'.$param.'%')->get();
        $bnd_res = Manuscript::where('binding', 'LIKE','%'.$param.'%')->get();

        $searchResults = $pl_res->merge($cm_res)
                                ->merge($po_res)
                                ->merge($doc_res)
                                ->merge($sub_res)
                                ->merge($subol_res)
                                ->merge($aut_res)
                                ->merge($aspn_res)
                                ->merge($pd_res)
                                ->merge($mat_res)
                                ->merge($fmt_res)
                                ->merge($bnd_res);

        return view('manuscripts.searchresults', ['manuscripts' => $searchResults, 'searchTerm' => $param]);
    }

    public function searchOne(Request $request) {
        $param = $request->search_parameters;
        $category = $request->category;
        $searchResults = Manuscript::where($category, 'LIKE','%'.$param.'%')->get();

        return view('manuscripts.searchresults', ['manuscripts' => $searchResults, 'searchTerm' => $param]);
    }

    // public function dumpAndDie(Request $request) {
    //     dd($request);
    // }
}

resources/views/manuscripts/create.blade.php
@extends ('layouts.base')

@section('title', 'Create New Manuscript')

@section('head_content')
    <link href="{{URL::asset('css/custom.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('heading', 'Add New Manuscript')

@section ('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="col-xs-12">
        <div class="text-center">    
            <br>
        </div>
    </div>

    <form action="{{ route('manuscripts.store')}}" method="post">
    {{-- <form action="{{ route('dumpAndDie')}}" method="post">     --}}
        @include('manuscripts.fields')
        <div class="form-group row">
            <div class="col-xs-12 text-center">
                <button type="submit" class="btn btn-primary">Add Manuscript</button>
            </div>
        </div>
        
    </form>
@endsection

resources/views/manuscripts/edit.blade.php
@extends('layouts.base')

@section('title', 'Edit Manuscript')

@section('head_content')
    <link href="{{URL::asset('css/custom.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('heading', 'Edit Manuscript')

@section('content')

<form action="{{ route('manuscripts.update', ['manuscript' => $manuscript]) }}" method="post">
    @csrf
    @method('PUT')
    @include('manuscripts.fields')
        <div class="form-group row">
            <div class="col-xs-12 text-center">
                <button type="submit" class="btn btn-primary">Update Manuscript</button>
            </div>
        </div>
</form>
    
@endsection

resources/views/manuscripts/fields.blade.php
{{-- Physical Location --}}
<div class="form-group row">
    
    <div class="form-label col-sm-2"><br>Physical Location</div>
    
    <div class="col-sm-8 form-field">
    <input class="form-control input-field" type="text" name="physical_location" id="physical_location" value="{{ old('physical_location', $manuscript->physical_location ?? null) }}" placeholder="Physical Location"/>
    </div>
</div>

{{-- Classmark --}}
<div class="form-group row">
    
    <div class="form-label col-sm-2"><br>Classmark</div>
    
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="classmark" id="classmark" value="{{ old('classmark', $manuscript->classmark ?? null) }}" placeholder="Classmark" />
    </div>
</div>

{{-- Subject(s) --}}
<div class="form-group row">
    
    <div class="form-label col-sm-2"><br>Subject(s)</div>  
    
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="subject" id="subject" value="{{ old('subject', $manuscript->subject ?? null) }}" placeholder="Subject(s)" />
    </div>
</div>

    
{{-- Subject (other language) --}}
<div class="form-group row">
    
    <div class="form-label col-sm-2"><br>Subject(s) (Other language)</div>  
    
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="subject_other_lang" id="subject_other_lang" value="{{ old('subject_other_lang', $manuscript->subject_other_lang ?? null) }}" placeholder="Subject(s) (Other language)" />
    </div>
</div>

{{-- Author(s) --}}
<div class="form-group row">
    <div class="col-sm-2 form-label"><br>Author(s)</div>  
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="author" id="author" value="{{ old('author', $manuscript->author ?? null) }}" placeholder="Author(s)" />
    </div>
</div>

{{-- Place of Origin --}}
<div class="form-group row">
    <div class="col-sm-2 form-label"><br>Place of Origin</div>  
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="place_of_origin" id="place_of_origin" value="{{ old('place_of_origin', $manuscript->place_of_origin ?? null) }}" placeholder="Place of Origin" />
    </div>
</div>

{{-- Date of Creation --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br>Date of Creation</div>
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="date_of_creation" id="date_of_creation" value="{{ old('date_of_creation', $manuscript->date_of_creation ?? null) }}" placeholder="Date of Creation" />
    </div>
</div>

{{-- Associated Persons --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br>Associated Persons</div>
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="associated_persons" id="associated_persons" value="{{ old('associated_persons', $manuscript->associated_persons ?? null) }}" placeholder="Associated Person(s)" />
    </div>
</div>

{{-- Physical Description --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br>Physical Description</div>
    <div class="col-sm-8 form-field">
        <textarea name="physical_description" id="physical_description" rows="5" class="form-control input-field" placeholder="Physical Description">{{ old('physical_description', $manuscript->physical_description ?? null) }}</textarea>
    </div>
</div>

{{-- Material --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br>Material</div>
    <div class="col-sm-8 form-field">
        <textarea name="material" id="material" rows="3" class="form-control input-field" value="{{ old('material', $manuscript->material ?? null) }}placeholder="Material"></textarea>
    </div>
</div>

{{-- Format --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br>Format</div>
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="format" id="format" value="{{ old('format', $manuscript->format ?? null) }}" placeholder="Format"/>
    </div>
</div>

{{-- Binding --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br>Binding</div>
    <div class="col-sm-8 form-field">
        <input class="form-control input-field" type="text" name="binding" id="binding" value="{{ old('binding', $manuscript->binding ?? null) }}" placeholder="Binding"/>
    </div>
</div>

<div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 form-field">
        <strong>Manuscript Images (from Google Drive) </strong>
    <a href="{{ route('google-drive') }}" target="_blank"> Get Image Links</a>
    </div>
</div> 


{{-- images --}}
<div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <textarea name="images" id="images" rows="10" class="form-control input-field" placeholder="Image link|width:height, eg. https://drive.google.com/open?id=ABCDEFGHIJKLMNOP|2000:6000">{{ old('images', $images ?? null) }}</textarea>
    </div>
</div>

{{-- Preview Image --}}
<div class="form-group row">
    <div class="form-label col-sm-2"><br></div>
    <div class="col-sm-8 form-field">
        <p>Please copy and paste one of the image links from above to use as a preview image in the manuscript listing.</p>
        <input class="form-control input-field" type="text" name="preview_image" id="preview_image" value="{{ old('preview_image', $manuscript->preview_image ?? null) }}" placeholder="Preview Image (DO NOT paste the width and height part, e.g. |2000:180) "/>
    </div>
</div>

@csrf

resources/views/manuscripts/images.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>Get Image Data from Google Drive</title>
    <meta charset="utf-8" />
  </head>
  <body>
    <h1>Google Drive Image Data</h1>

    <!--Add buttons to initiate auth sequence and sign out-->
    <button id="authorize_button" style="display: none;">Authorize</button>
    <button id="signout_button" style="display: none;">Sign Out</button>

    <p>Navigate to the folder containing the manuscript, then select the folder ID in the URL (after folder/), and paste it in the box below.</p>
    <p>ภาสภไทย</p>
    <div>
        <img src="{{ URL::asset('/img/googledrive.jpg') }}" alt="GoogleDrive">
    </div>


    <input type="text" name="folder_name" id="folder_name" placeholder="Enter folder name here" style="display: none;">
    <br>
    <button id="search_button" style="display: none;">Search</button>

    <pre id="numFiles" style="white-space: pre-wrap"></pre>

    <pre id="content" style="white-space: pre-wrap;"></pre>

    <script type="text/javascript">
      // Client ID and API key from the Developer Console
      var CLIENT_ID = '412078386097-g9lvenu8uckm569927uh7d9qdpp4a77m.apps.googleusercontent.com';
      var API_KEY = 'AIzaSyBVYTroJq4FTNAQaRxpLiQstzFxb0HLo30';

      // Array of API discovery doc URLs for APIs used by the quickstart
      var DISCOVERY_DOCS = ["https://www.googleapis.com/discovery/v1/apis/drive/v3/rest"];

      // Authorization scopes required by the API; multiple scopes can be
      // included, separated by spaces.
      var SCOPES = 'https://www.googleapis.com/auth/drive.metadata.readonly';

      var authorizeButton = document.getElementById('authorize_button');
      var signoutButton = document.getElementById('signout_button');
      var folderName = document.getElementById('folder_name');
      var serachButton = document.getElementById('search_button');
	    var folderId = "";
      var pre = document.getElementById('content');
      var numFilesPre = document.getElementById('numFiles');
      /**
       *  On load, called to load the auth2 library and API client library.
       */
      function handleClientLoad() {
        gapi.load('client:auth2', initClient);
      }

      /**
       *  Initializes the API client library and sets up sign-in state
       *  listeners.
       */
      function initClient() {
        gapi.client.init({
          apiKey: API_KEY,
          clientId: CLIENT_ID,
          discoveryDocs: DISCOVERY_DOCS,
          scope: SCOPES
        }).then(function () {
          // Listen for sign-in state changes.
          gapi.auth2.getAuthInstance().isSignedIn.listen(updateSigninStatus);

          // Handle the initial sign-in state.
          updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
          authorizeButton.onclick = handleAuthClick;
          signoutButton.onclick = handleSignoutClick;
          serachButton.onclick = handleSearchClick;
        }, function(error) {
          appendPre(JSON.stringify(error, null, 2));
        });
      }

      /**
       *  Called when the signed in status changes, to update the UI
       *  appropriately. After a sign-in, the API is called.
       */
      function updateSigninStatus(isSignedIn) {
        if (isSignedIn) {
          authorizeButton.style.display = 'none';
          signoutButton.style.display = 'block';
          serachButton.style.display = 'block';
          folderName.style.display = 'block';
        } else {
          authorizeButton.style.display = 'block';
          signoutButton.style.display = 'none';
          serachButton.style.display = 'none';
          folderName.style.display = 'none';
        }
      }

      /**
       *  Sign in the user upon button click.
       */
      function handleAuthClick(event) {
        gapi.auth2.getAuthInstance().signIn();
      }
      
      function handleSearchClick(event) {
        listFiles();
      }
      /**
       *  Sign out the user upon button click.
       */
      function handleSignoutClick(event) {
        gapi.auth2.getAuthInstance().signOut();
      }

      /**
       * Append a pre element to the body containing the given message
       * as its text node. Used to display the results of the API call.
       *
       * @param {string} message Text to be placed in pre element.
       */
      function appendPre(message) {
        var textContent = document.createTextNode(message + '\n');
        pre.appendChild(textContent);
      }

      function appendNumFiles(message) {
          var textContent = document.createTextNode(message + '\n');
          numFilesPre.appendChild(textContent);
      }

      /**
       * Print files. 
       */
      function listFiles() {
        pre.innerHTML = "";
        numFilesPre.innerHTML = "";
        folderId = folderName.value;  
        console.log(folderId);
        gapi.client.drive.files.list({
			'pageSize': 1000,
			'fields': "nextPageToken, files(id, name, imageMediaMetadata)",
			'q': "'" + folderId + "' in parents"
			}).then(function(response) {
          var files = response.result.files;
          if (files && files.length > 0) {
			appendNumFiles('Number of files: ' + files.length);
			appendNumFiles(' ');
            for (var i = 0; i < files.length; i++) {
              
			  var file = files[i];
              var id = file.id;
              var metadata = file.imageMediaMetadata;
              appendPre('https://drive.google.com/uc?id=' + file.id + '|' + metadata.width + ':' + metadata.height);
            }
          } else {
            appendPre('No files found.');
          }
        });
      }

    </script>

    <script async defer src="https://apis.google.com/js/api.js"
      onload="this.onload=function(){};handleClientLoad()"
      onreadystatechange="if (this.readyState === 'complete') this.onload()">
    </script>
  </body>
</html>

resources/views/manuscripts/index.blade.php
@extends('layouts.base')

@section('title', 'List of Manuscripts')

@section('head_content')
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/custom.css') }}">    
@endsection

@section('heading', 'List of Manuscripts')

@section('content')
    
    {{-- <div class="row"><div class="col-xs-8 col-xs-offset-2"></div> --}}

    @include('manuscripts.listing')
    
    
@endsection

resources/views/manuscripts/listing.blade.php
@foreach ($manuscripts as $manuscript)

        <div class="row middlerow">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="well well-lg">
                    <div class="text-center">
                        <a href="{{ route('manuscripts.show', ['manuscript' => $manuscript]) }}"><img src="{{ $manuscript->preview_image }}" alt="" width="150"></a>
                        
                    <div>
                        <br><a href="{{ route('manuscripts.show', ['manuscript' => $manuscript]) }}">{{ $manuscript->place_of_origin }}</a>
                    </div>
                    
                    <div>
                        {{ $manuscript->date_of_creation }}
                    </div>
                </div>
                <br>
                    <div>
                    <p>{{ $manuscript->physical_description }}</p>
                    </div>
                </div>
            </div>
        </div>
        
    @endforeach

resources/views/manuscripts/search.blade.php
@extends('layouts.base')

@section('title', 'Search Manuscripts')
@section('heading', 'Search Manuscripts')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <p style="font-size: 20px;">You can search our manuscript library here. Enter search terms below. </p><br>
        </div>
    </div>
    <h3>Search All Fields</h3>
    <br>
    <form action="{{ route('manuscripts.search') }}" method="post">
        
        <div class="form-group row">
            <div class="col-sm-10 form-field">
                <input class="form-control input-field" type="text" name="search_parameters" id="search_parameters" placeholder="Enter search terms" />
            </div>
        {{-- </div>

        <div class="form-group row"> --}}
            <div class="col-xs-12 text-center">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
        @csrf
    </form>
    <br>

    <h3>Search by Category</h3>
    <br>

    <form action="{{ route('manuscripts.searchOne') }}" method="post">

    <div class="form-group row">
        <div class="form-label col-sm-2">
            <select name="category" id="category" class="form-control" required>
                <option value="" disabled selected>Category</option>
                <option value="physical_location">Physical Location</option>
                <option value="classmark">Classmark</option>
                <option value="place_of_origin">Place of Origin</option>
                <option value="subject">Subject(s)</option>
                <option value="subject_other_lang">Subject(s) (Other language)</option>
                <option value="author">Author(s)</option>
                <option value="date_of_creation">Date of Creation</option>
                <option value="associated_persons">Associated Person(s)</option>
                <option value="physical_description">Physical Description</option>
                <option value="material">Material</option>
                <option value="format">Format</option>
                <option value="binding">Binding</option>
            </select>
        </div>
        <div class="col-sm-8 form-field">
            <input class="form-control input-field" type="text" name="search_parameters" id="search_parameters" placeholder="Enter search terms" />
        </div>

    {{-- </div>
    <div class="form-group row"> --}}
        <div class="col-xs-12 text-center">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
    @csrf
    {{-- <form action="route('manuscripts.searchOne'" method="post"> --}}

    </form>
@endsection

resources/views/manuscripts/searchresults.blade.php
@extends('layouts.base')

@section('title', 'Search Results')

@section('head_content')
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/custom.css') }}">    
@endsection

@section('heading', 'Search Results')

@section('content')
    
    @if (count($manuscripts) == 0)
        <div class="text-center padded-div">
            <h4>Your search for '{{ $searchTerm }}' did not return any results.</h4><br>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ route('manuscripts.showSearchForm') }}'">Back to Search Form</button>
        </div>
    @else
        <div class="row">
            <div class="col-sm-3">
                <a href="{{ route('manuscripts.showSearchForm') }}">< Search Form</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    <h4>You searched for: {{ $searchTerm }}</h4><br>
                    <h5>Your search returned {{ count($manuscripts) }} results.</h5>
                </div>
                <br>
            </div>
        </div>
        @include('manuscripts.listing')
    @endif

    

@endsection